name: "Acer Predator Triton 500 P515-51"
cmdPort: 0x66 #! required
dataPort: 0x62 #! required
zones: 
  - name: System
    address: 0xA9
    min: 0x00
    max: 0xff
  - name: CPU Zone
    address: 0xA8 # required!
    min: 0x00 # default 0x00
    max: 0xff # default 0xff
    fans:
      - name: Fan 1
        address: 0x93 # required!
        auto: 0x04 # default 0x04
        manual: 0x14 # default 0x14
        wrReg: 0x94 # required!
        rdReg: 0x95 # required!
        min: 0xff # default 0xff
        max: 0x00 # default 0x00
  - name: GPU Zone
    address: 0xB8
    min: 0x00
    max: 0xff
    fans:
      - name: Fan 1
        address: 0x96 # required!
        auto: 0x04
        manual: 0x14
        wrReg: 0x97
        rdReg: 0x98
        min:    0xff
        max:    0x1D
      - name: Fan 2
        address: 0x9A
        auto: 0x04
        manual: 0x14
        wrReg: 0x9B
        rdReg: 0x9C
        min:    0xff
        max:    0x00
config: 
  max: 0x5A # default 0x5a (90 C)
  min: 0x00 # default 0x00 (0 C)
  levels: # if no stages it then use 25% step
    - enterTemp: 30.0
      freq: 40.0
    - enterTemp: 40.0
      freq: 50.0
    - enterTemp: 60.0
      freq: 70.0
    - enterTemp: 80.0
      freq: 90.0
    - enterTemp: 90.0
      freq: 100.0