name: "Build and package PSense project"
on:
  push:
    branches: ["feature/packages"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build static binaries
      uses: skynet-core/nim@v1.2
    - name: Archive psense binary
      uses: actions/upload-artifact@v2
      with:
        name: psense
        path: ${{ github.workspace }}/psense
    - name: Archive psensectl binary
      uses: actions/upload-artifact@v2
      with:
        name: psensectl
        path: ${{ github.workspace }}/psensepkg/cli/psensectl
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - name: Generate nfpm config
      id: nfpm-cfg
      shell: bash
      env:
          GIT_REF: ${{ github.ref }}
      run: |
        if [[ $a == "*refs/tags/*" ]]; then
          git_tag=$(git describe --tags `git rev-list --tags --max-count=1` | tr -d 'v')
        else
          git_tag=$(cat psense.nimble | grep version | head -n 1 | cut -d '=' -f2 | awk '{$1=$1};1' | sed 's|\"||g')
        fi
        cat ./nfpm.template.yaml | sed -e "s|@git_tag|$git_tag|g" > ./nfpm.yaml
        echo "::set-output name=TAG::$git_tag"
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Install Github-Release
      shell: bash
      run: go get github.com/github-release/github-release
    - name: Publish builds
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: github-release info -u skynet-core -r npsense