name: testing-deploy
on:
  push:
    branches:
    - testing/*
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out code'
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}  
    - name: Setup SSH Keys and known_hosts
      env:
        SECRET: '${{ secrets.KEY_PASS }}'
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        cat<<EOF | tee $(pwd)/ask_pass.sh
        #!/usr/bin/env sh
        echo $SECRET
        EOF
        chmod +x $(pwd)/ask_pass.sh
        mkdir -p ~/.ssh
        ssh-keyscan wehack.network >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        export SSH_ASKPASS=$(pwd)/ask_pass.sh
        #export DISPLAY=localhost:0.0
        ssh-add - <<< "${{ secrets.SSH_PRIV_KEY }}"
    - name: 'Test SFTP access'
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        sftp github@wehack.network lpwd