name: testing-deploy
on:
  push:
    branches:
    - testing/*
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out code'
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}    
    - name: 'Test SFTP access'
      run: |
        cat<<EOF | awk '{$1=$1};1' | base64 -d - >/tmp/id_ed25519_github
        ${{ secrets.SSH_PRIV_KEY }}
        EOF
        cat /tmp/id_ed25519_github
        sftp -i /tmp/id_ed25519_github github@wehack.network lpwd