name: test
on: 
  push:
    branches:
      - feature/*
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out code'
      uses: actions/checkout@v2
    - name: 'Run tests'
      uses: skynet-core/nim@v1.2
      with:
        command: 'nimble test -y'